base_dir: log/ae_lstm_4_ga/
data:
  batch_size: 200
  dataset: data/ae_lstm/hanoi.csv
  test_batch_size: 1
  test_size: 0.2
  valid_size: 0.2
log_level: INFO
model:
  rnn_units: 50
  activation: relu
  input_dim: 5
  output_dim: 1
  seq_len: 48
  horizon: 1
  timestep: 4
train:
  dropout: 0.5
  epochs: 300
  optimizer: adam
  patience: 300
  loss: mse
